[package]
name = "magika-cbind"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
magika= { version = "0.1.0-rc.2" }
ort = "2.0.0-rc.8"

[build-dependencies]
cbindgen = "0.26.0"
